RH_G4S/urls.py
from django.urls import path
from . import views
#from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView  

app_name = 'RH_G4S'

urlpatterns = [

    # Accueil
    path('', views.accueil, name='accueil'),  

    # Modèle
    path('modele', views.modele, name='modele'),
    path('modele_PS_rembourse', views.modele_PS_rembourse, name='modele_PS_rembourse'),
    path('modele_PS_non_rembourse', views.modele_PS_non_rembourse, name='modele_PS_non_rembourse'),  
    path('modele_sans_PS', views.modele_sans_PS, name='modele_sans_PS'), 

    # Lettre
    path('lettre', views.lettre, name='lettre'),
    path('lettre_sans_PS', views.lettre_sans_PS, name='lettre_sans_PS'),
    path('lettre_avec_PS', views.lettre_avec_PS, name='lettre_avec_PS'), 
    path('lettre_PS_rembourse', views.lettre_PS_rembourse, name='lettre_PS_rembourse'),

    # Contact 
    path('contact', views.contact, name='contact'),

    ]

monsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RH_G4S.urls')),
]


templates/lettre/lettre.html
{% extends 'static/base.html' %}
   
    {% block title %}

        <title>Lettre</title>

    {% endblock %}


    {% block content %}

            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Lettre de démission sans Préavis</center></h1>
                        </div>
                    </div>
                </div>
            </section>

            <section id="information" class="py-5 bg-light">
                <p class="lead mb-4 text-md-center" > 
                    Veuillez cliquer sur l'un des boutons ci-dessous : <br>
                    Pour créer une lettre de démission sans préavis et ... ,  <br>         
                </p>

                <p class="lead mb-4 text-md-center" >  
                   
                    <a href="{% url 'RH_G4S:lettre_sans_PS' %}" title="PS : Prêt Scolaire" type="button" class="btn btn-secondary">Sans PS</a>

                    <a href="{% url 'RH_G4S:lettre_PS_rembourse' %}" type="button" title="PS : Prêt Scolaire" class="btn btn-secondary">Avec PS dont le remboursement a débuté</a> 

                    <a href="{% url 'RH_G4S:lettre_avec_PS' %}" title="PS : Prêt Scolaire" type="button" class="btn btn-secondary">Avec PS dont le remboursement n'a pas débuté<br></a>
                    
                    
                </p>

            </section> 
            
    {% endblock %}

templates/lettre/lettre_PS_rembourse.html
{% extends 'static/base.html' %}
{% load crispy_forms_tags %}   

    {% block title %}

        <title>Lettre</title>

    {% endblock %}


    {% block content %}

        <div class="container"> 
            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Lettre sans Préavis avec PS remboursé en partie </center></h1>
                        
                        </div>
                    </div>
                </div>
            </section>

            <section class="container text-md-center">
                <h3> <mark>  Veuillez renseigner le formulaire ci-dessous relatif aux informations sur l'employé </mark> </h3>
            </section>
            <br> <br>

            <section class="container">   
                <form method="POST"  action="{% url 'RH_G4S:lettre_PS_rembourse' %}">  
                    {% csrf_token %}

                    {% crispy formulaire %}
                    
                    <br>  <br>
                </form>
            </section>

            <section>
                <br> <br>

            </section>
        </div>
    {% endblock %}       

templates/lettre/lettre_avec_PS.html
{% extends 'static/base.html' %}
{% load crispy_forms_tags %}   

    {% block title %}

        <title>Lettre</title>

    {% endblock %}


    {% block content %}

        <div class="container"> 
            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Lettre sans Préavis et avec PS </center></h1>
                        
                        </div>
                    </div>
                </div>
            </section>

            <section class="container text-md-center">
                <h3> <mark>  Veuillez renseigner le formulaire ci-dessous relatif aux informations sur l'employé </mark> </h3>
            </section>
            <br> <br>

            <section class="container">   
                <form method="POST"  action="{% url 'RH_G4S:lettre_avec_PS' %}">  
                    {% csrf_token %}

                    {% crispy formulaire %}
                    
                    <br>  <br>
                </form>
            </section>

            <section>
                <br> <br>

            </section>
        </div>
    {% endblock %}       

templates/lettre/lettre_sans_PS.html
{% extends 'static/base.html' %}
{% load crispy_forms_tags %}   

    {% block title %}

        <title>Lettre</title>

    {% endblock %}


    {% block content %}

        <div class="container"> 
            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Lettre sans Préavis et sans PS </center></h1>
                        
                        </div>
                    </div>
                </div>
            </section>

            <section class="container text-md-center">
               <h3> <mark>  Veuillez renseigner le formulaire ci-dessous relatif aux informations sur l'employé </mark> </h3>
            </section>
            <br> <br>

            <section class="container">   
                <form method="POST"  action="{% url 'RH_G4S:lettre_sans_PS' %}">  
                    {% csrf_token %}

                    {% crispy formulaire %}
                    
                    <br>  <br>
                </form>
            </section>

            <section>
                <br> <br>

            </section>
        </div>
    {% endblock %}       